// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5XBiIo1eLrpP-bDk4zsAvApU3VYXasZg',
    appId: '1:411765749460:web:272cfedd1562dc672ced41',
    messagingSenderId: '411765749460',
    projectId: 'fluttapp-d0337',
    authDomain: 'fluttapp-d0337.firebaseapp.com',
    storageBucket: 'fluttapp-d0337.firebasestorage.app',
    measurementId: 'G-23LC8RCG11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANmQxL-kSvRNXpN5mbWooDCbT3wLdO8gs',
    appId: '1:411765749460:android:815ea0b0fabd6a572ced41',
    messagingSenderId: '411765749460',
    projectId: 'fluttapp-d0337',
    storageBucket: 'fluttapp-d0337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj8isouVU6q1V6MfaYAPmepoXMNW5uCQA',
    appId: '1:411765749460:ios:0b48ef71905c0c002ced41',
    messagingSenderId: '411765749460',
    projectId: 'fluttapp-d0337',
    storageBucket: 'fluttapp-d0337.firebasestorage.app',
    iosClientId: '411765749460-umep381jbvk1hq5ivcfpetq5kttq4i31.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj8isouVU6q1V6MfaYAPmepoXMNW5uCQA',
    appId: '1:411765749460:ios:0b48ef71905c0c002ced41',
    messagingSenderId: '411765749460',
    projectId: 'fluttapp-d0337',
    storageBucket: 'fluttapp-d0337.firebasestorage.app',
    iosClientId: '411765749460-umep381jbvk1hq5ivcfpetq5kttq4i31.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5XBiIo1eLrpP-bDk4zsAvApU3VYXasZg',
    appId: '1:411765749460:web:ca755f4776895e982ced41',
    messagingSenderId: '411765749460',
    projectId: 'fluttapp-d0337',
    authDomain: 'fluttapp-d0337.firebaseapp.com',
    storageBucket: 'fluttapp-d0337.firebasestorage.app',
    measurementId: 'G-TQXD30EMTL',
  );
}
